# Generated by Django 3.0.5 on 2021-03-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1),
        ),
    ]
