# Generated by Django 3.0.5 on 2021-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritor', '0002_auto_20210308_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='libros_publicados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
