# Generated by Django 3.0.5 on 2021-03-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('narrativa', models.CharField(max_length=20, verbose_name='narrativa')),
                ('genero', models.CharField(max_length=20, verbose_name='genero')),
                ('sinopsis', models.TextField(default='', max_length=500, verbose_name='sinopsis')),
                ('contenido', models.TextField(default='', verbose_name='contenido')),
                ('status', models.BooleanField(default=False, verbose_name='terminada')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
    ]
