# Generated by Django 3.0.5 on 2021-03-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historias',
            name='genero',
            field=models.CharField(default='', max_length=20, verbose_name='genero'),
        ),
    ]
