# Generated by Django 3.0.5 on 2021-03-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historia', '0002_auto_20210309_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('puntaje', models.PositiveIntegerField(default=0, max_length=1, verbose_name='puntaje')),
                ('autor_valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historia_valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia.Historias')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contenido', models.TextField(max_length=500, verbose_name='contenido')),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historia_comentario', models.ManyToManyField(to='historia.Historias')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
    ]
