# Generated by Django 3.0.5 on 2021-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_comentarios_valoraciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoraciones',
            name='puntaje',
            field=models.PositiveIntegerField(default=0, verbose_name='puntaje'),
        ),
    ]
