# Generated by Django 3.0.5 on 2021-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_auto_20210309_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historias',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='historias',
            name='genero',
            field=models.CharField(blank=True, max_length=20, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='historias',
            name='sinopsis',
            field=models.TextField(blank=True, max_length=500, verbose_name='sinopsis'),
        ),
    ]
